apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: {{template "fullname" .}}
    heritage: {{.Release.Service | quote}}
    release: {{.Release.Name | quote}}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  name: {{template "fullname" .}}
spec:
  replicas: 1
  selector:
    name: {{template "fullname" .}}
  template:
    metadata:
      labels:
        name: {{template "fullname" .}}
        release: {{.Release.Name | quote}}
    spec:
      containers:
      - name: influxdb
        image: "{{.Values.image}}:{{.Values.imageTag}}"
        imagePullPolicy: {{default "Always" .Values.pullPolicy}}
        args:
          - "-config=/etc/influxdb/influxdb.toml"
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        - mountPath: /etc/influxdb
          name: influxdb-config
      volumes:
      - name: influxdb-config
        configMap:
          name: {{template "fullname" .}}
      - name: influxdb-storage
        emptyDir: {}
          
