apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: {{ template "fullname" . }}
    name: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ template "fullname" . }}
spec:
  replicas: 1
  selector:
    k8s-app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        k8s-app: {{ template "fullname" . }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: heapster
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{default "Always" .Values.pullPolicy}}
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default.svc.cluster.local?kubeletPort=10250&kubeletHttps=true
        - --sink=influxdb:http://{{ template "influxdb.fullname" . }}:{{ default 8086 .Values.influxdb.apiPort }}
