apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Heapster
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ template "fullname" . }}
spec:
  type: NodePort
  ports:
  - port: {{ default 80 .Values.httpPort }}
    targetPort: {{ default 8082 .Values.targetPort }}
    nodePort: {{ default 32500 .Values.nodePort }}
  selector:
    k8s-app: {{ template "fullname" . }}
